# Generated by Django 2.2.3 on 2019-11-09 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': "Answer's Choices",
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questype', models.CharField(max_length=15)),
                ('marks', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Class')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('Sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Subject')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theory_question', models.TextField(max_length=500)),
                ('correct_ans', models.CharField(max_length=200)),
                ('theory_pic', models.FileField(blank=True, null=True, upload_to='images/')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Questions')),
            ],
            options={
                'verbose_name_plural': 'Theories',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=15)),
                ('created_by', models.CharField(max_length=15)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Subject')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Topic')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Quiz'),
        ),
        migrations.CreateModel(
            name='Mcqs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mcq_question', models.TextField(max_length=500)),
                ('mcq_picture', models.FileField(blank=True, null=True, upload_to='images/')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Questions')),
            ],
            options={
                'verbose_name_plural': 'MCQS',
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.AnswerChoice')),
                ('mcqs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Mcqs')),
            ],
            options={
                'verbose_name_plural': 'Correct Answers',
            },
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='mcqs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizapp.Mcqs'),
        ),
    ]
